(cl:defpackage sena_msgs-srv
  (:use )
  (:export
   "BALLHANDLE"
   "<BALLHANDLE-REQUEST>"
   "BALLHANDLE-REQUEST"
   "<BALLHANDLE-RESPONSE>"
   "BALLHANDLE-RESPONSE"
   "SHOOT"
   "<SHOOT-REQUEST>"
   "SHOOT-REQUEST"
   "<SHOOT-RESPONSE>"
   "SHOOT-RESPONSE"
  ))

