// Generated by gencpp from file sena_common/PPoint.msg
// DO NOT EDIT!


#ifndef SENA_COMMON_MESSAGE_PPOINT_H
#define SENA_COMMON_MESSAGE_PPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sena_common
{
template <class ContainerAllocator>
struct PPoint_
{
  typedef PPoint_<ContainerAllocator> Type;

  PPoint_()
    : angle(0.0)
    , radius(0.0)  {
    }
  PPoint_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , radius(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;

   typedef float _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::sena_common::PPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sena_common::PPoint_<ContainerAllocator> const> ConstPtr;

}; // struct PPoint_

typedef ::sena_common::PPoint_<std::allocator<void> > PPoint;

typedef boost::shared_ptr< ::sena_common::PPoint > PPointPtr;
typedef boost::shared_ptr< ::sena_common::PPoint const> PPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sena_common::PPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sena_common::PPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sena_common::PPoint_<ContainerAllocator1> & lhs, const ::sena_common::PPoint_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.radius == rhs.radius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sena_common::PPoint_<ContainerAllocator1> & lhs, const ::sena_common::PPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sena_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sena_common::PPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sena_common::PPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_common::PPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_common::PPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_common::PPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_common::PPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sena_common::PPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29d7d0dfcbdb558f82b1c2caff948161";
  }

  static const char* value(const ::sena_common::PPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29d7d0dfcbdb558fULL;
  static const uint64_t static_value2 = 0x82b1c2caff948161ULL;
};

template<class ContainerAllocator>
struct DataType< ::sena_common::PPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sena_common/PPoint";
  }

  static const char* value(const ::sena_common::PPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sena_common::PPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n"
"float32 radius\n"
;
  }

  static const char* value(const ::sena_common::PPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sena_common::PPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sena_common::PPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sena_common::PPoint_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENA_COMMON_MESSAGE_PPOINT_H
