// Generated by gencpp from file sena_msgs/Angle.msg
// DO NOT EDIT!


#ifndef SENA_MSGS_MESSAGE_ANGLE_H
#define SENA_MSGS_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sena_msgs
{
template <class ContainerAllocator>
struct Angle_
{
  typedef Angle_<ContainerAllocator> Type;

  Angle_()
    : theta(0.0)  {
    }
  Angle_(const ContainerAllocator& _alloc)
    : theta(0.0)  {
  (void)_alloc;
    }



   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::sena_msgs::Angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sena_msgs::Angle_<ContainerAllocator> const> ConstPtr;

}; // struct Angle_

typedef ::sena_msgs::Angle_<std::allocator<void> > Angle;

typedef boost::shared_ptr< ::sena_msgs::Angle > AnglePtr;
typedef boost::shared_ptr< ::sena_msgs::Angle const> AngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sena_msgs::Angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sena_msgs::Angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sena_msgs::Angle_<ContainerAllocator1> & lhs, const ::sena_msgs::Angle_<ContainerAllocator2> & rhs)
{
  return lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sena_msgs::Angle_<ContainerAllocator1> & lhs, const ::sena_msgs::Angle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sena_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sena_msgs::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sena_msgs::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_msgs::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_msgs::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_msgs::Angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_msgs::Angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sena_msgs::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7328b114b91e2487fcf12e1581a80145";
  }

  static const char* value(const ::sena_msgs::Angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7328b114b91e2487ULL;
  static const uint64_t static_value2 = 0xfcf12e1581a80145ULL;
};

template<class ContainerAllocator>
struct DataType< ::sena_msgs::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sena_msgs/Angle";
  }

  static const char* value(const ::sena_msgs::Angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sena_msgs::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta\n"
;
  }

  static const char* value(const ::sena_msgs::Angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sena_msgs::Angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sena_msgs::Angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sena_msgs::Angle_<ContainerAllocator>& v)
  {
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENA_MSGS_MESSAGE_ANGLE_H
