// Generated by gencpp from file sena_msgs/BallHandleResponse.msg
// DO NOT EDIT!


#ifndef SENA_MSGS_MESSAGE_BALLHANDLERESPONSE_H
#define SENA_MSGS_MESSAGE_BALLHANDLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sena_msgs
{
template <class ContainerAllocator>
struct BallHandleResponse_
{
  typedef BallHandleResponse_<ContainerAllocator> Type;

  BallHandleResponse_()
    : BallIsHolding(0)  {
    }
  BallHandleResponse_(const ContainerAllocator& _alloc)
    : BallIsHolding(0)  {
  (void)_alloc;
    }



   typedef int64_t _BallIsHolding_type;
  _BallIsHolding_type BallIsHolding;





  typedef boost::shared_ptr< ::sena_msgs::BallHandleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sena_msgs::BallHandleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BallHandleResponse_

typedef ::sena_msgs::BallHandleResponse_<std::allocator<void> > BallHandleResponse;

typedef boost::shared_ptr< ::sena_msgs::BallHandleResponse > BallHandleResponsePtr;
typedef boost::shared_ptr< ::sena_msgs::BallHandleResponse const> BallHandleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sena_msgs::BallHandleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sena_msgs::BallHandleResponse_<ContainerAllocator1> & lhs, const ::sena_msgs::BallHandleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.BallIsHolding == rhs.BallIsHolding;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sena_msgs::BallHandleResponse_<ContainerAllocator1> & lhs, const ::sena_msgs::BallHandleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sena_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sena_msgs::BallHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_msgs::BallHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_msgs::BallHandleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "371e9ec4fdab9c30277b932f121cf460";
  }

  static const char* value(const ::sena_msgs::BallHandleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x371e9ec4fdab9c30ULL;
  static const uint64_t static_value2 = 0x277b932f121cf460ULL;
};

template<class ContainerAllocator>
struct DataType< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sena_msgs/BallHandleResponse";
  }

  static const char* value(const ::sena_msgs::BallHandleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 BallIsHolding\n"
"\n"
;
  }

  static const char* value(const ::sena_msgs::BallHandleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BallIsHolding);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallHandleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sena_msgs::BallHandleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sena_msgs::BallHandleResponse_<ContainerAllocator>& v)
  {
    s << indent << "BallIsHolding: ";
    Printer<int64_t>::stream(s, indent + "  ", v.BallIsHolding);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENA_MSGS_MESSAGE_BALLHANDLERESPONSE_H
