// Generated by gencpp from file sena_msgs/FrameToFrame.msg
// DO NOT EDIT!


#ifndef SENA_MSGS_MESSAGE_FRAMETOFRAME_H
#define SENA_MSGS_MESSAGE_FRAMETOFRAME_H

#include <ros/service_traits.h>


#include <sena_msgs/FrameToFrameRequest.h>
#include <sena_msgs/FrameToFrameResponse.h>


namespace sena_msgs
{

struct FrameToFrame
{

typedef FrameToFrameRequest Request;
typedef FrameToFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FrameToFrame
} // namespace sena_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sena_msgs::FrameToFrame > {
  static const char* value()
  {
    return "405de59229ff9ecc65cfa6d1fe41484d";
  }

  static const char* value(const ::sena_msgs::FrameToFrame&) { return value(); }
};

template<>
struct DataType< ::sena_msgs::FrameToFrame > {
  static const char* value()
  {
    return "sena_msgs/FrameToFrame";
  }

  static const char* value(const ::sena_msgs::FrameToFrame&) { return value(); }
};


// service_traits::MD5Sum< ::sena_msgs::FrameToFrameRequest> should match
// service_traits::MD5Sum< ::sena_msgs::FrameToFrame >
template<>
struct MD5Sum< ::sena_msgs::FrameToFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sena_msgs::FrameToFrame >::value();
  }
  static const char* value(const ::sena_msgs::FrameToFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sena_msgs::FrameToFrameRequest> should match
// service_traits::DataType< ::sena_msgs::FrameToFrame >
template<>
struct DataType< ::sena_msgs::FrameToFrameRequest>
{
  static const char* value()
  {
    return DataType< ::sena_msgs::FrameToFrame >::value();
  }
  static const char* value(const ::sena_msgs::FrameToFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sena_msgs::FrameToFrameResponse> should match
// service_traits::MD5Sum< ::sena_msgs::FrameToFrame >
template<>
struct MD5Sum< ::sena_msgs::FrameToFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sena_msgs::FrameToFrame >::value();
  }
  static const char* value(const ::sena_msgs::FrameToFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sena_msgs::FrameToFrameResponse> should match
// service_traits::DataType< ::sena_msgs::FrameToFrame >
template<>
struct DataType< ::sena_msgs::FrameToFrameResponse>
{
  static const char* value()
  {
    return DataType< ::sena_msgs::FrameToFrame >::value();
  }
  static const char* value(const ::sena_msgs::FrameToFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENA_MSGS_MESSAGE_FRAMETOFRAME_H
