// Generated by gencpp from file sena_msgs/KinematicsInverse.msg
// DO NOT EDIT!


#ifndef SENA_MSGS_MESSAGE_KINEMATICSINVERSE_H
#define SENA_MSGS_MESSAGE_KINEMATICSINVERSE_H

#include <ros/service_traits.h>


#include <sena_msgs/KinematicsInverseRequest.h>
#include <sena_msgs/KinematicsInverseResponse.h>


namespace sena_msgs
{

struct KinematicsInverse
{

typedef KinematicsInverseRequest Request;
typedef KinematicsInverseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KinematicsInverse
} // namespace sena_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sena_msgs::KinematicsInverse > {
  static const char* value()
  {
    return "28edd23182264a435d8e5f00f1e42018";
  }

  static const char* value(const ::sena_msgs::KinematicsInverse&) { return value(); }
};

template<>
struct DataType< ::sena_msgs::KinematicsInverse > {
  static const char* value()
  {
    return "sena_msgs/KinematicsInverse";
  }

  static const char* value(const ::sena_msgs::KinematicsInverse&) { return value(); }
};


// service_traits::MD5Sum< ::sena_msgs::KinematicsInverseRequest> should match
// service_traits::MD5Sum< ::sena_msgs::KinematicsInverse >
template<>
struct MD5Sum< ::sena_msgs::KinematicsInverseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sena_msgs::KinematicsInverse >::value();
  }
  static const char* value(const ::sena_msgs::KinematicsInverseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sena_msgs::KinematicsInverseRequest> should match
// service_traits::DataType< ::sena_msgs::KinematicsInverse >
template<>
struct DataType< ::sena_msgs::KinematicsInverseRequest>
{
  static const char* value()
  {
    return DataType< ::sena_msgs::KinematicsInverse >::value();
  }
  static const char* value(const ::sena_msgs::KinematicsInverseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sena_msgs::KinematicsInverseResponse> should match
// service_traits::MD5Sum< ::sena_msgs::KinematicsInverse >
template<>
struct MD5Sum< ::sena_msgs::KinematicsInverseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sena_msgs::KinematicsInverse >::value();
  }
  static const char* value(const ::sena_msgs::KinematicsInverseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sena_msgs::KinematicsInverseResponse> should match
// service_traits::DataType< ::sena_msgs::KinematicsInverse >
template<>
struct DataType< ::sena_msgs::KinematicsInverseResponse>
{
  static const char* value()
  {
    return DataType< ::sena_msgs::KinematicsInverse >::value();
  }
  static const char* value(const ::sena_msgs::KinematicsInverseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENA_MSGS_MESSAGE_KINEMATICSINVERSE_H
