// Generated by gencpp from file sena_msgs/KinematicsForward.msg
// DO NOT EDIT!


#ifndef SENA_MSGS_MESSAGE_KINEMATICSFORWARD_H
#define SENA_MSGS_MESSAGE_KINEMATICSFORWARD_H

#include <ros/service_traits.h>


#include <sena_msgs/KinematicsForwardRequest.h>
#include <sena_msgs/KinematicsForwardResponse.h>


namespace sena_msgs
{

struct KinematicsForward
{

typedef KinematicsForwardRequest Request;
typedef KinematicsForwardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KinematicsForward
} // namespace sena_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sena_msgs::KinematicsForward > {
  static const char* value()
  {
    return "bf1862fd720e27b736dafd380ee1763b";
  }

  static const char* value(const ::sena_msgs::KinematicsForward&) { return value(); }
};

template<>
struct DataType< ::sena_msgs::KinematicsForward > {
  static const char* value()
  {
    return "sena_msgs/KinematicsForward";
  }

  static const char* value(const ::sena_msgs::KinematicsForward&) { return value(); }
};


// service_traits::MD5Sum< ::sena_msgs::KinematicsForwardRequest> should match
// service_traits::MD5Sum< ::sena_msgs::KinematicsForward >
template<>
struct MD5Sum< ::sena_msgs::KinematicsForwardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sena_msgs::KinematicsForward >::value();
  }
  static const char* value(const ::sena_msgs::KinematicsForwardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sena_msgs::KinematicsForwardRequest> should match
// service_traits::DataType< ::sena_msgs::KinematicsForward >
template<>
struct DataType< ::sena_msgs::KinematicsForwardRequest>
{
  static const char* value()
  {
    return DataType< ::sena_msgs::KinematicsForward >::value();
  }
  static const char* value(const ::sena_msgs::KinematicsForwardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sena_msgs::KinematicsForwardResponse> should match
// service_traits::MD5Sum< ::sena_msgs::KinematicsForward >
template<>
struct MD5Sum< ::sena_msgs::KinematicsForwardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sena_msgs::KinematicsForward >::value();
  }
  static const char* value(const ::sena_msgs::KinematicsForwardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sena_msgs::KinematicsForwardResponse> should match
// service_traits::DataType< ::sena_msgs::KinematicsForward >
template<>
struct DataType< ::sena_msgs::KinematicsForwardResponse>
{
  static const char* value()
  {
    return DataType< ::sena_msgs::KinematicsForward >::value();
  }
  static const char* value(const ::sena_msgs::KinematicsForwardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENA_MSGS_MESSAGE_KINEMATICSFORWARD_H
