// Generated by gencpp from file sena_msgs/KinematicsForwardRequest.msg
// DO NOT EDIT!


#ifndef SENA_MSGS_MESSAGE_KINEMATICSFORWARDREQUEST_H
#define SENA_MSGS_MESSAGE_KINEMATICSFORWARDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sena_msgs/Velocity.h>

namespace sena_msgs
{
template <class ContainerAllocator>
struct KinematicsForwardRequest_
{
  typedef KinematicsForwardRequest_<ContainerAllocator> Type;

  KinematicsForwardRequest_()
    : input()  {
    }
  KinematicsForwardRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sena_msgs::Velocity_<ContainerAllocator>  _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicsForwardRequest_

typedef ::sena_msgs::KinematicsForwardRequest_<std::allocator<void> > KinematicsForwardRequest;

typedef boost::shared_ptr< ::sena_msgs::KinematicsForwardRequest > KinematicsForwardRequestPtr;
typedef boost::shared_ptr< ::sena_msgs::KinematicsForwardRequest const> KinematicsForwardRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator1> & lhs, const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator1> & lhs, const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sena_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f88504877018a01455a97248300901c7";
  }

  static const char* value(const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf88504877018a014ULL;
  static const uint64_t static_value2 = 0x55a97248300901c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sena_msgs/KinematicsForwardRequest";
  }

  static const char* value(const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sena_msgs/Velocity input\n"
"\n"
"================================================================================\n"
"MSG: sena_msgs/Velocity\n"
"float64 v_left\n"
"float64 v_right\n"
"float64 v_back\n"
;
  }

  static const char* value(const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinematicsForwardRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sena_msgs::KinematicsForwardRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    s << std::endl;
    Printer< ::sena_msgs::Velocity_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENA_MSGS_MESSAGE_KINEMATICSFORWARDREQUEST_H
