// Generated by gencpp from file sena_msgs/Shoot.msg
// DO NOT EDIT!


#ifndef SENA_MSGS_MESSAGE_SHOOT_H
#define SENA_MSGS_MESSAGE_SHOOT_H

#include <ros/service_traits.h>


#include <sena_msgs/ShootRequest.h>
#include <sena_msgs/ShootResponse.h>


namespace sena_msgs
{

struct Shoot
{

typedef ShootRequest Request;
typedef ShootResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Shoot
} // namespace sena_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sena_msgs::Shoot > {
  static const char* value()
  {
    return "5f7b2fca861afe65dc92d3f6a153bbec";
  }

  static const char* value(const ::sena_msgs::Shoot&) { return value(); }
};

template<>
struct DataType< ::sena_msgs::Shoot > {
  static const char* value()
  {
    return "sena_msgs/Shoot";
  }

  static const char* value(const ::sena_msgs::Shoot&) { return value(); }
};


// service_traits::MD5Sum< ::sena_msgs::ShootRequest> should match
// service_traits::MD5Sum< ::sena_msgs::Shoot >
template<>
struct MD5Sum< ::sena_msgs::ShootRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sena_msgs::Shoot >::value();
  }
  static const char* value(const ::sena_msgs::ShootRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sena_msgs::ShootRequest> should match
// service_traits::DataType< ::sena_msgs::Shoot >
template<>
struct DataType< ::sena_msgs::ShootRequest>
{
  static const char* value()
  {
    return DataType< ::sena_msgs::Shoot >::value();
  }
  static const char* value(const ::sena_msgs::ShootRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sena_msgs::ShootResponse> should match
// service_traits::MD5Sum< ::sena_msgs::Shoot >
template<>
struct MD5Sum< ::sena_msgs::ShootResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sena_msgs::Shoot >::value();
  }
  static const char* value(const ::sena_msgs::ShootResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sena_msgs::ShootResponse> should match
// service_traits::DataType< ::sena_msgs::Shoot >
template<>
struct DataType< ::sena_msgs::ShootResponse>
{
  static const char* value()
  {
    return DataType< ::sena_msgs::Shoot >::value();
  }
  static const char* value(const ::sena_msgs::ShootResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENA_MSGS_MESSAGE_SHOOT_H
