// Generated by gencpp from file sena_msgs/Velocity.msg
// DO NOT EDIT!


#ifndef SENA_MSGS_MESSAGE_VELOCITY_H
#define SENA_MSGS_MESSAGE_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sena_msgs
{
template <class ContainerAllocator>
struct Velocity_
{
  typedef Velocity_<ContainerAllocator> Type;

  Velocity_()
    : v_left(0.0)
    , v_right(0.0)
    , v_back(0.0)  {
    }
  Velocity_(const ContainerAllocator& _alloc)
    : v_left(0.0)
    , v_right(0.0)
    , v_back(0.0)  {
  (void)_alloc;
    }



   typedef double _v_left_type;
  _v_left_type v_left;

   typedef double _v_right_type;
  _v_right_type v_right;

   typedef double _v_back_type;
  _v_back_type v_back;





  typedef boost::shared_ptr< ::sena_msgs::Velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sena_msgs::Velocity_<ContainerAllocator> const> ConstPtr;

}; // struct Velocity_

typedef ::sena_msgs::Velocity_<std::allocator<void> > Velocity;

typedef boost::shared_ptr< ::sena_msgs::Velocity > VelocityPtr;
typedef boost::shared_ptr< ::sena_msgs::Velocity const> VelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sena_msgs::Velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sena_msgs::Velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sena_msgs::Velocity_<ContainerAllocator1> & lhs, const ::sena_msgs::Velocity_<ContainerAllocator2> & rhs)
{
  return lhs.v_left == rhs.v_left &&
    lhs.v_right == rhs.v_right &&
    lhs.v_back == rhs.v_back;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sena_msgs::Velocity_<ContainerAllocator1> & lhs, const ::sena_msgs::Velocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sena_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sena_msgs::Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sena_msgs::Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_msgs::Velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sena_msgs::Velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_msgs::Velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sena_msgs::Velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sena_msgs::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f242f54cda2fad8ff062e66077f57b70";
  }

  static const char* value(const ::sena_msgs::Velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf242f54cda2fad8fULL;
  static const uint64_t static_value2 = 0xf062e66077f57b70ULL;
};

template<class ContainerAllocator>
struct DataType< ::sena_msgs::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sena_msgs/Velocity";
  }

  static const char* value(const ::sena_msgs::Velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sena_msgs::Velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 v_left\n"
"float64 v_right\n"
"float64 v_back\n"
;
  }

  static const char* value(const ::sena_msgs::Velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sena_msgs::Velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_left);
      stream.next(m.v_right);
      stream.next(m.v_back);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sena_msgs::Velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sena_msgs::Velocity_<ContainerAllocator>& v)
  {
    s << indent << "v_left: ";
    Printer<double>::stream(s, indent + "  ", v.v_left);
    s << indent << "v_right: ";
    Printer<double>::stream(s, indent + "  ", v.v_right);
    s << indent << "v_back: ";
    Printer<double>::stream(s, indent + "  ", v.v_back);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENA_MSGS_MESSAGE_VELOCITY_H
